apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configuration
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-configuration/
    repoURL: https://github.com/rbo/gitops-problem-1.git
    targetRevision: main
